flowchart LR
	classDef sc fill:#080
	classDef ec fill:#f00
	node-start((( ))):::sc
	--> node-1(填报人)
	==> node-2(岗位1)
	==> node-3(岗位2)
	===> node-4(岗位3)
	--> node-end((( ))):::ec
	node-3 & node-4 -. 退回 .-> node-1
