flowchart LR
	classDef sc fill:#080
	classDef ec fill:#f00
	node-start((( ))):::sc
	--> node-1(填报人)
	==> node-2(岗位1)
	==> node-3(岗位2)
	===> node-4s(岗位3s) & node-4(岗位3)
	===> node-5(岗位4)
	--> node-end((( ))):::ec
	node-4 -. 退回 .-> node-2
	node-4s -. 退回 .-> node-1
	node-5 -. 退回 .-> node-3
